#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioUI.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Views\Home\Home.cshtml"
    using ScenarioUI.ViewGenerators;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Home\Home.cshtml"
    using ScenarioUI.Views.Shared;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Home : WebViewGenerator
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("\r\n");


            
            #line 6 "..\..\Views\Home\Home.cshtml"
  
    Layout = new Layout
    {
        HttpContext = HttpContext,
        Title = "💉 Prepare for testing"
    };


            
            #line default
            #line hidden
WriteLiteral("\r\n<table class=\"table\">\r\n    <thead class=\"thead-dark\">\r\n        <tr>\r\n          " +
"  <th>\r\n                <i class=\"fas fa-apple-alt\"></i> \r\n                TestN" +
"ame\r\n            </th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");


            
            #line 24 "..\..\Views\Home\Home.cshtml"
         foreach (var test in Tests)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n                    ");


            
            #line 28 "..\..\Views\Home\Home.cshtml"
               Write(test);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");


            
            #line 31 "..\..\Views\Home\Home.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");


        }
    }
}
#pragma warning restore 1591
